### ISSUE TITLE
Change Sound Channels default tweak 128->64

### ISSUE THREAD

**Issue by Zebouski** [brndd/vanilla-tweaks#11]
When sound channels are set to 128, many others and I have experienced crashing/freezing in naxx, like from the mass spells from gargoyles, kt spawns, faerlina trash all cast their spells to the entire 40man at once.

With sound channels down to 64, the freezing has stopped and we can still hear most the sounds in 40mans. I suggest this be made the new default, and people can still go 128 with the flag if they choose to, maybe with a warning in the --help that 128+ channels may cause crashing.

**Comment by brndd** [comment]
Thanks for the report. I made a new release to change this. 128 was probably more than a little overkill anyway.
