### ISSUE TITLE
Cant change Frilldistance

### ISSUE THREAD

**Issue by Mosch0512** [brndd/vanilla-tweaks#12]
when typing
/console frilldistance 100

it does not change anything

**Comment by brndd** [comment]
This value is hardcoded in 1.12.1. To change it you'll have to run the patcher from the command line and specify it in the `--frilldistance` parameter, e.g. `vanilla-tweaks.exe --frilldistance 100 WoW.exe`.

**Comment by Mosch0512** [comment]
thx
