### ISSUE TITLE
Fog and higher farclip

### ISSUE THREAD

**Issue by Haaxor1689** [brndd/vanilla-tweaks#15]
Any values of farclip above around 1500 result in seemingly the same result since fog doesn't extend any further than that no matter how high the farclip is. Is there an option that controls fog distance?

**Comment by brndd** [comment]
For what it's worth, I had a quick peek at this some months ago and forgot to comment here, but I think fog distance values are based on the various weather conditions and zone atmospheres, and as such aren't really practical to patch like this (excepting maybe a patch that disables fog altogether, but that wouldn't really look good). I'm closing this as out of scope for this project.

**Comment by Haaxor1689** [comment]
thanks for letting me know either way :)
