### ISSUE TITLE
Add camera fixes

### ISSUE THREAD

**Issue by refaim** [brndd/vanilla-tweaks#17]
https://mega.nz/folder/ykZglR6J#LOG-hGTqJ3ZOTROwTlG5Hw

> These patched executables fix the ancient client bugs that cause your mouse cursor to reset to the center of your screen and / or cause your camera to jump to a different location when clicking. Rename to "Wow.exe" to use with patching tools such as vanilla-tweaks. Source code and offsets are available in the Assembly folder.

Also see [discussion in the Turtle WoW Discord](https://discord.com/channels/466622455805378571/988866055222984744/1099262068009484309):

> xxx: I don't think I ever saw that happen but is it related to camera sometimes snapping to random position when you hold down right click?
> yyy: this should also fix that bug, they're related

**Comment by brndd** [comment]
> [16:54]Bon: all i had to do was make the cursor position reset function point to the variable that stores your mouse coords when you click, and move the stored position away from the edge of the screen if it's too close
> [16:54]Bon: so the bug still happens, but it doesn't matter because it resets to where it should be

Pasting these here for the record so I don't have to look them up on Discord every time.

**Comment by Arcitec** [comment]
Adding more details since it's interesting. So basically, the patch was created by Bon (discord name bonbigz), and this is the full description that he posted on the Turtle WoW discord in December 2023:

> i patched vanilla, tbc, and wotlk clients, which can be found here:
https://mega.nz/folder/ykZglR6J#LOG-hGTqJ3ZOTROwTlG5Hw
> 
> i don't plan on patching any other clients, but everything necessary to apply it yourself can be found in the Assembly folder if you're willing to learn how to use Ghidra
> 
> the problem is that there's a race condition in the cursor reset code, sometimes the cursor will reset before it releases control of the camera and snap your camera or send your cursor to the center of your screen when you release left or right click
> 
> the patch gets around the problem by setting the stored cursor position variable to the position of your cursor when you started controlling the camera instead of the center of your screen (the race condition still happens, but it doesn't matter since it resets to the position it already is)
> 
> but this creates a new problem where you can't control your camera if your mouse is on the edge of your screen, so i also move your cursor slightly away from the edge of your screen if it's too close
