### ISSUE TITLE
my ping is going red after useing the patch 1.6

### ISSUE THREAD

**Issue by hzf86cnxp** [brndd/vanilla-tweaks#19]
Hello Sir
first of all，thanks you for the patch，it is wonderful.
i'm a chinese living in china（guagndong）playing wow（everlook sever）[OS：win 11 22H2 CPU I5 10400F +RTX2080+RAM 16G]
my Clients is download in  https://wowdl.net/  （World-of-Warcraft-1.12.1.5875-zhCN or World-of-Warcraft-1.12.1.5875-enUS）
when i login wow，usually i will turn on my proxy server，before useing the patch，my ping is between 150ms~200ms，is green，and my action is ok .since i use the patch（the patch is really good，i want to use it）my ping will go up to 600ms or higher，my action is very difficulty
i want to know if there is anyone the same or is there solution？
thanks you very much，like your patch very

**Comment by brndd** [comment]
Does this happen with both the zhCN and the enUS clients, or just one or the other? The patcher might not work correctly with clients other than enUS because the offsets could be different.

One thing you could try is using the command line parameters of the patcher to disable every patch, then re-enable them one by one to see which one is causing the ping issue.

**Comment by hzf86cnxp** [comment]
你好，这是自动回复！
我的邮箱已经收到你的邮件
我会尽快查看并亲自回复
如有紧急事宜请致电
谢谢！

**Comment by hzf86cnxp** [comment]
Thanks for your reply
both the zhCN and the enUS clients will Appear the same question.but in this afternoon，i have make a mistake. i am going to click the proxy server，but i just click the repair network and everthing is going best. my ping is green now
i just want to thanks again，and if there is anyone the same as me，i sugesanks for your reply
both the zhCN and the enUS clients will Appear the same question.but in this afternoon，i have make a mistake. i am going to click the proxy server，but i just click the repair network and everthing is going best. my ping is green now
i just want to thanks again，and if there is anyone the same as me，i sug first ‘repair network’，and maybe will work
thanks for the Owner！
