### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by WuVenus** [brndd/vanilla-tweaks#23]
How do I customize

There is no tutorial, I really need it

**Comment by brndd** [comment]
This had some discussion over at #8. I was unable to replicate it, which leads me to believe that it only happens when there's an update available (which servers like Turtle often ship).

**Comment by WuVenus** [comment]
What should I do

**Comment by brndd** [comment]
Try launching the game from the default WoW.exe and letting it update.

**Comment by WuVenus** [comment]
Turtle-wow It can be used. No damage will occur

Everlook File corruption will occur
![148538-c4fcc489da56531b5e13ab3891f24a60](https://github.com/brndd/vanilla-tweaks/assets/144596429/f85fec6d-037b-43f4-a843-fd51a363de1c)
