### ISSUE TITLE
Is there a way to make this work for 4.3.4?

### ISSUE THREAD

**Issue by 01aokijii** [brndd/vanilla-tweaks#25]

**Comment by brndd** [comment]
Not really. I don't think most of the fixes here are even necessary on that client, as they should be built-in features. Field of view might be the one thing that can't easily be changed in modern clients, and there are existing patchers for that.

**Comment by 01aokijii** [comment]
I was looking for a fix for the camera glitch but kinda fixed it by setting mouse polling rate to 250
