### ISSUE TITLE
MaxCameraDistance

### ISSUE THREAD

**Issue by SSDDX-Devs** [brndd/vanilla-tweaks#3]
Hello Sir
Thank you for your work
This QoL patcher works really well but when we use max FOV value(3.14) its zoom out camera much but its side angles looks so odd
so please add MaxCameraDistance patch  also? 

with FOV: 3.14 and CameraDistance: 50 (Game Default)
![image](https://user-images.githubusercontent.com/19153689/180380026-a13c7c9f-8896-4fd8-96f2-c1ea920dfe60.png)

with FOV: 1.5708 (Game Default) and CameraDistance: 100 (i managed to edit it using camera-setting.txt file present inside wtf/account/accountname/servername/playername/camera-setting.txt but its not a permanent solution if i zoom in a little bit it will reset to 50 automatically)
![image](https://user-images.githubusercontent.com/19153689/180380174-98223974-0983-4507-97ca-5909d7d45f4d.png)

**Comment by brndd** [comment]
Added in v1.4.0. Let me know if it doesn't work satisfactorily.

One thing I noticed while testing the patch was that the `/console CameraDistanceMax` doesn't actually match the internal value that gets written to config. I assume it's multiplied by some value to be better compatible with the camera distance slider in the options. Either way, patching the value to 100 (using `--maxcameradistance 100` parameter) and running `/console CameraDistanceMax 100` still seems to work and allows you to zoom out as far as with the camera-setting.txt trick.
