### ISSUE TITLE
Unable to remove sound in background

### ISSUE THREAD

**Issue by MrToothless** [brndd/vanilla-tweaks#31]
Running the VAnilla-tweaks in Powershell with the correct flag to remove sound in background results in the WoW executable being patched correctly but sound still plays in the background..

**Comment by brndd** [comment]
The patcher doesn't currently support undoing any of the patches. This is why you're encouraged to keep your original executable around. That issue is tracked in #28.

**Comment by MrToothless** [comment]
Untrue. 

Running "./vanilla-tweaks --no-sound-in-background wow.exe" off the default exe does not correctly disable the sound in background as expected.
