### ISSUE TITLE
Solo raid icons

### ISSUE THREAD

**Issue by burner1024** [brndd/vanilla-tweaks#4]
I can't find an addon for this, so I assume it's a client limitation.
In party/raid, you can assign icons to creatures. Classic also allows to do that when solo, but not vanilla.
It's quite helpful when trying to find a mob. Would it be possible to enable that?

**Comment by brndd** [comment]
Without looking into it at all, I'm pretty sure this feature would be part of the Blizzard Lua UI, so patching it in would involve modifying framexml rather than the executable.
