### ISSUE TITLE
Auto FOV selection

### ISSUE THREAD

**Issue by shikulja** [brndd/vanilla-tweaks#7]
Depending on the current resolution, FOV can be calculated.
The task is not trivial, for three OS at the same time. But it will simplify patching for people who do not have to understand, and who have monitors other than 16: 9

**Comment by sambonz** [comment]
Hi! I love all the tweaks - thank you.
But, I prefer the default FOV in the vanilla client on my 16:9 monitor. How do I disable the FOV patch, but retain all the other tweaks?
Thanks in advance!

**Comment by shikulja** [comment]
@sambonz
vanilla-tweaks.exe --no-fov WoW.exe
see readme and --help command

**Comment by shikulja** [comment]
SuperWoW (SuperAPI) solves this problem, almost
