### ISSUE TITLE
[Feature] Rotate Minimap

### ISSUE THREAD

**Issue by Soromeister** [brndd/vanilla-tweaks#9]
Currently, the minimap works like so:

Pivot is on the minimap, so minimap is static, but player arrow rotates in the direction that the player is facing

Could it be possible to make it just like in Retail, where pivot is on the player arrow (always facing north/up), while the minimap rotates based on where the player is looking?

**Comment by brndd** [comment]
This would be a FrameXML feature, I expect, and therefore out of scope. Might even be possible with an addon.
